name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  WAFFLE_BUCKET: ${{ secrets.WAFFLE_BUCKET }}

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1.9.0
      with:
        elixir-version: 1.12.4
        otp-version: 24.0.3

    - name: Restore dependencies cache
      uses: actions/cache@v2
      id: mix-cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get --only test

    - name: Compile & lint dependencies
      run: mix compile --warnings-as-errors
      env:
        MIX_ENV: test

    - name: Check Formatting
      run: mix format --check-formatted

    - name: Run tests
      run: mix test

